<?php exit;?>
itemid,ID,
mid,模块ID,
oid,订单ID,
buyer,买家,
seller,卖家,
title,商品名称,
amount,金额,
seller_company,卖家公司,
seller_contract,卖家合同,
seller_time,卖家时间,
buyer_company,买家公司,
buyer_contract,买家合同,
buyer_time,买家时间,
addtime,添加时间,
status,状态,