<?php
$names = array (
  'article' => '资讯',
  'brand' => '品牌展示',
  'buy' => '采购清单',
  'channel' => '频道',
  'club' => '商圈',
  'contact' => '联系方式',
  'down' => '下载',
  'exhibit' => '展会',
  'footer' => '公共页脚',
  'group' => '团购',
  'header' => '公共页头',
  'honor' => '荣誉资质',
  'index' => '公司首页',
  'info' => '招商代理',
  'introduce' => '公司介绍',
  'job' => '人才招聘',
  'know' => '知道',
  'link' => '友情链接',
  'mall' => '商城',
  'moment' => '动态',
  'news' => '公司新闻',
  'photo' => '公司相册',
  'quote' => '行情',
  'resume' => '简历',
  'sell' => '供应',
  'special' => '专题',
  'video' => '视频',
);
?>