<?php
$names = array (
  'list' => '默认列表',
  'list-article' => '文章列表',
  'list-brand' => '品牌列表',
  'list-buy' => '求购列表',
  'list-club' => '帖子列表',
  'list-club-group' => '商圈列表',
  'list-club-reply' => '帖子回复',
  'list-company' => '公司列表',
  'list-down' => '下载列表',
  'list-exhibit' => '展会列表',
  'list-group' => '团购列表',
  'list-info' => '信息列表',
  'list-job' => '招聘列表',
  'list-know' => '知道列表',
  'list-mall' => '商品列表',
  'list-mall-sec' => '商品秒杀',
  'list-moment' => '动态列表',
  'list-moment-topic' => '动态话题列表',
  'list-photo' => '图库列表',
  'list-quote' => '行情列表',
  'list-quote-price' => '行情报价列表',
  'list-quote-product' => '行情产品列表',
  'list-resume' => '简历列表',
  'list-search-kw' => '搜索关键词',
  'list-search-tip' => '搜索提示',
  'list-sell' => '供应列表',
  'list-space' => '空间列表',
  'list-special' => '专题列表',
  'list-special-type' => '专题分类',
  'list-thumb' => '图片列表',
  'list-video' => '视频列表',
);
?>